import { useState, useEffect } from "react";
import { GoogleReview } from "@/types";

interface UseGoogleReviewsReturn {
  reviews: GoogleReview[] | null;
  isLoading: boolean;
}

export function useGoogleReviews(
  locale: string,
  languageCode: string
): UseGoogleReviewsReturn {
  const [reviews, setReviews] = useState<GoogleReview[] | null>(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    // In a real build, we import the JSON generated by scripts/fetch-reviews.mjs
    // For now, we simulate an async load of that local data
    const loadReviews = async () => {
      try {
        // dynamic import to avoid bundling if file is missing (though we ensured it exists)
        const module = await import("@/data/google-reviews.json");
        const data = module.default as GoogleReview[];

        if (data && data.length > 0) {
          setReviews(data);
        } else {
          setReviews(null); // Fallback to manual
        }
      } catch (error) {
        console.warn("Could not load Google Reviews JSON:", error);
        setReviews(null);
      } finally {
        setIsLoading(false);
      }
    };

    loadReviews();
  }, [locale, languageCode]);

  return { reviews, isLoading };
}
